### ISSUE TITLE
Plugin causes Npp crash with Npp v7.9.4

### ISSUE THREAD

**Issue by lxuio** [Hsilgos/nppsaveasadmin#31]
### ErrorLogs:
Name der fehlerhaften Anwendung: notepad++.exe, Version: 7.9.4.0, Zeitstempel: 0x604ea4e0
Name des fehlerhaften Moduls: clr.dll, Version: 4.8.4341.0, Zeitstempel: 0x602301f3
Ausnahmecode: 0xc0000005
Fehleroffset: 0x000000000066a450
ID des fehlerhaften Prozesses: 0x42d8
Startzeit der fehlerhaften Anwendung: 0x01d71c76e41ca48e
Pfad der fehlerhaften Anwendung: C:\Program Files\Notepad++\notepad++.exe
Pfad des fehlerhaften Moduls: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Berichtskennung: 9039a1dd-9ca2-4ae0-a636-e9815758f1b3
Vollständiger Name des fehlerhaften Pakets: 

Name der fehlerhaften Anwendung: notepad++.exe, Version: 7.9.4.0, Zeitstempel: 0x604ea4e0
Name des fehlerhaften Moduls: clr.dll, Version: 4.8.4341.0, Zeitstempel: 0x602301f3
Ausnahmecode: 0xc0000005
Fehleroffset: 0x000000000066a450
ID des fehlerhaften Prozesses: 0x3fd8
Startzeit der fehlerhaften Anwendung: 0x01d71c7594c0f927
Pfad der fehlerhaften Anwendung: C:\Program Files\Notepad++\notepad++.exe
Pfad des fehlerhaften Moduls: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Berichtskennung: c9bd2989-d413-4e5f-9908-c409795fb649
Vollständiger Name des fehlerhaften Pakets: 

### Tryed: 
```
C:\WINDOWS\system32>SFC/SCANNOW

Systemsuche wird gestartet. Dieser Vorgang kann einige Zeit dauern.

Überprüfungsphase der Systemsuche wird gestartet.
Überprüfung 100 % abgeschlossen.

Der Windows-Ressourcenschutz hat beschädigte Dateien gefunden und erfolgreich repariert.
Bei Onlinereparaturen finden Sie Details in der CBS-Protokolldatei unter
windir\Logs\CBS\CBS.log. Beispiel C:\Windows\Logs\CBS\CBS.log. Bei Offlinereparaturen
finden Sie Details in der durch das /OFFLOGFILE-Kennzeichen angegebenen Protokolldatei.

C:\WINDOWS\system32>
```

and

`C:\WINDOWS\system32>DISM.exe /Online /Cleanup-image /Restorehealth`

only de-Installation of the Plugin helped

**Comment by Hsilgos** [comment]
I assume Notepad++ solved this issue with smart installer, sorry for inconvenience
