### ISSUE TITLE
Save file bug.

### ISSUE THREAD

**Issue by HoytRen** [Hsilgos/nppsaveasadmin#32]
V1.0.211 on 8.1.9.1 on win10 21H2 after edit the last line of a text file, the host file for example, this plugin add some extra chars like 'cn', 'nn' at the end of the file when save the file. You will not see the chars before reopen the file.

**Comment by Hsilgos** [comment]
Hi, @HoytRen 

I tried to reproduce and failed.
I have:
- Windows 10 Pro
- Notepad++ 8.2
- Save As Admin: 1.0.211

I tried both x64 and x86 versions.
Please describe your setup and exact steps which lead to the bug

**Comment by HoytRen** [comment]
Hi, @Hsilgos

After I upgrade NPP to 8.1.9.3, I don't see this again. I guess we can close this issue. Thanks for help.
